apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah-pipeline
spec:
  workspaces:
    - name: src-workspace
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: src-workspace
      params:
        - name: url
          value: http://gitea.wingwill.xyz/tekton-ci/ci-hello-world.git
        - name: deleteExisting
          value: "true"
    # - name: build
    #   taskRef:
    #     name: buildah
    #   runAfter:
    #     - fetch-repository
    #   params:
    #     - name: IMAGE
    #       value: docker.io/{YOUR_DOCKERHUB_REPOSITORY_NAME}
    #     - name: IMAGE_PUSH_SECRET_NAME
    #       value: image-push-secrets
    #   workspaces:
    #     - name: source
    #       workspace: myworkspace