apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: src-repo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

# kubectl create -f .... create a pvc 