---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tektonhub-ci-cd-pipeline
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: image
    description: reference of the image to build
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: <GITEA_SOURCE_REPO>
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: kaniko
    taskRef:
      name: kaniko
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.image)
    - name: EXTRA_ARGS
      value:
        - --skip-tls-verify
  - name: verify-digest
    runAfter:
    - kaniko
    params:
    - name: digest
      value: $(tasks.kaniko.results.IMAGE_DIGEST)
    taskSpec:
      params:
      - name: digest
      steps:
      - name: bash
        image: ubuntu
        script: |
          echo $(params.digest)          
          case .$(params.digest) in
            ".sha"*) exit 0 ;;
            *)       echo "Digest value is not correct" && exit 1 ;;
          esac
  
  - name: create-deployment
    taskRef:
      name: kubernetes-actions
    runAfter:
      - verify-digest
    params:
      - name: script
        value: |
          kubectl apply -f $(workspaces.manifest-dir.path)/kubernetes-manifests
          
    workspaces:
      - name: manifest-dir
        workspace: shared-workspace
