apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-hello-world
  template:
    metadata:
      labels:
        app: nodejs-hello-world
    spec:
      imagePullSecrets:
        - name: harbor-registry-key 
      containers:
        - name: server
          image: <HARBOR_REGISTRY_URL>/molly/nodejs-hello-world:latest
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5


